version: '3'
services:
    server:
        container_name: mtons-blog
        image: langhsu/mblog:latest
        environment:
            TZ: Asia/Shanghai
        ports:
        - "8080:8080"
        restart: always