spring:
    datasource:
        #schema: classpath*:scripts/schema.sql
        #continue-on-error: false
        #sql-script-encoding: utf-8
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://129.211.3.40:3306/db_mblog?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: wanghf!@#$
    flyway:
        enabled: true
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: validate #配置自动建表：updata:没有表新建，有表更新操作,控制台显示建表语句
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        properties:
            hibernate.format_sql: true
            hibernate.naming.physical-strategy: org.hibernate.scripts.model.naming.PhysicalNamingStrategyStandardImpl
            hibernate.cache.use_second_level_cache: false
            hibernate.search.default.directory_provider: filesystem
            hibernate.search.default.indexBase: ${site.location}/storage/indexes
    datasource1:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://129.211.3.40:3306/db_chat?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
        username: root
        password: wanghf!@#$


mybatis:
    mapper-locations : classpath:mybatis/mapper/*.xml
    type-aliases-package : com.mtons.mblog.pojo



